### ISSUE TITLE
Can't pickle <function <lambda> ...

### ISSUE THREAD

**Issue by coderjoonwoo** [cj-mills/pytorch-keypoint-rcnn-tutorial-code#1]
Running pytorch-keypoint-r-cnn-training-labelme.ipynb generates the "Error Message" below:
How can I pass this?
BTW, from DataLoader source, I see the following warning:
    .. warning:: If the ``spawn`` start method is used, :attr:`worker_init_fn`
                 cannot be an unpicklable object, e.g., a lambda function. See
                 :ref:`multiprocessing-best-practices` on more details related
                 to multiprocessing in PyTorch.
(D:\jupyter8890\ is my local path of anaconda installation)

<<<<< Error Message >>>>> starts here
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
Cell In[37], line 1
----> 1 train_loop(model=model, 
      2            train_dataloader=train_dataloader,
      3            valid_dataloader=valid_dataloader,
      4            optimizer=optimizer, 
      5            lr_scheduler=lr_scheduler, 
      6            device=torch.device(device), 
      7            epochs=epochs, 
      8            checkpoint_path=checkpoint_path,
      9            use_scaler=True)

Cell In[33], line 34, in train_loop(model, train_dataloader, valid_dataloader, optimizer, lr_scheduler, device, epochs, checkpoint_path, use_scaler)
     31 # Loop over the epochs
     32 for epoch in tqdm(range(epochs), desc="Epochs"):
     33     # Run a training epoch and get the training loss
---> 34     train_loss = run_epoch(model, train_dataloader, optimizer, lr_scheduler, device, scaler, epoch, is_training=True)
     35     # Run an evaluation epoch and get the validation loss
     36     with torch.no_grad():

Cell In[32], line 27, in run_epoch(model, dataloader, optimizer, lr_scheduler, device, scaler, epoch_id, is_training)
     24 progress_bar = tqdm(total=len(dataloader), desc="Train" if is_training else "Eval")
     26 # Iterate over data batches
---> 27 for batch_id, (inputs, targets) in enumerate(dataloader):
     28     
     29     # Move inputs and targets to the specified device
     30     inputs = torch.stack(inputs).to(device)
     31     # Extract the ground truth bounding boxes and labels

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\site-packages\torch\utils\data\dataloader.py:435, in DataLoader.__iter__(self)
    433 if self.persistent_workers and self.num_workers > 0:
    434     if self._iterator is None:
--> 435         self._iterator = self._get_iterator()
    436     else:
    437         self._iterator._reset(self)

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\site-packages\torch\utils\data\dataloader.py:388, in DataLoader._get_iterator(self)
    386 else:
    387     self.check_worker_number_rationality()
--> 388     return _MultiProcessingDataLoaderIter(self)

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\site-packages\torch\utils\data\dataloader.py:1038, in _MultiProcessingDataLoaderIter.__init__(self, loader)
   1031 w.daemon = True
   1032 # NB: Process.start() actually take some time as it needs to
   1033 #     start a process and pass the arguments over via a pipe.
   1034 #     Therefore, we only add a worker to self._workers list after
   1035 #     it started, so that we do not call .join() if program dies
   1036 #     before it starts, and __del__ tries to join but will get:
   1037 #     AssertionError: can only join a started process.
-> 1038 w.start()
   1039 self._index_queues.append(index_queue)
   1040 self._workers.append(w)

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\multiprocessing\process.py:121, in BaseProcess.start(self)
    118 assert not _current_process._config.get('daemon'), \
    119        'daemonic processes are not allowed to have children'
    120 _cleanup()
--> 121 self._popen = self._Popen(self)
    122 self._sentinel = self._popen.sentinel
    123 # Avoid a refcycle if the target function holds an indirect
    124 # reference to the process object (see bpo-30775)

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\multiprocessing\context.py:224, in Process._Popen(process_obj)
    222 @staticmethod
    223 def _Popen(process_obj):
--> 224     return _default_context.get_context().Process._Popen(process_obj)

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\multiprocessing\context.py:336, in SpawnProcess._Popen(process_obj)
    333 @staticmethod
    334 def _Popen(process_obj):
    335     from .popen_spawn_win32 import Popen
--> 336     return Popen(process_obj)

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\multiprocessing\popen_spawn_win32.py:95, in Popen.__init__(self, process_obj)
     93 try:
     94     reduction.dump(prep_data, to_child)
---> 95     reduction.dump(process_obj, to_child)
     96 finally:
     97     set_spawning_popen(None)

File D:\jupyter8890\anaconda3\envs\kprcnn\Lib\multiprocessing\reduction.py:60, in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)

PicklingError: Can't pickle <function <lambda> at 0x00000237EF3162A0>: attribute lookup <lambda> on __main__ failed

**Comment by cj-mills** [comment]
Hi @coderjoonwoo,

I address this in the [tutorial](https://christianjmills.com/posts/pytorch-train-keypoint-rcnn-tutorial/#getting-started-with-the-code), but Python multiprocessing works differently on Windows compared to Linux. I’ve made a dedicated version of the tutorial code to run on Windows:

* [notebooks/pytorch-keypoint-r-cnn-training-labelme-windows.ipynb](https://github.com/cj-mills/pytorch-keypoint-rcnn-tutorial-code/blob/main/notebooks/pytorch-keypoint-r-cnn-training-labelme-windows.ipynb)
* [notebooks/windows_utils.py](https://github.com/cj-mills/pytorch-keypoint-rcnn-tutorial-code/blob/main/notebooks/windows_utils.py)

**Comment by coderjoonwoo** [comment]
> Hi @coderjoonwoo,
> 
> I address this in the [tutorial](https://christianjmills.com/posts/pytorch-train-keypoint-rcnn-tutorial/#getting-started-with-the-code), but Python multiprocessing works differently on Windows compared to Linux. I’ve made a dedicated version of the tutorial code to run on Windows:
> 
> * [notebooks/pytorch-keypoint-r-cnn-training-labelme-windows.ipynb](https://github.com/cj-mills/pytorch-keypoint-rcnn-tutorial-code/blob/main/notebooks/pytorch-keypoint-r-cnn-training-labelme-windows.ipynb)
> * [notebooks/windows_utils.py](https://github.com/cj-mills/pytorch-keypoint-rcnn-tutorial-code/blob/main/notebooks/windows_utils.py)

Yes, I am using Windows, should have paid attention to *_windows file. Now it works. Thank you for quick help.
